### ISSUE TITLE
com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated

### ISSUE THREAD

**Issue by elharo** [googleapis/java-bigquerydatatransfer#11]
WARNING] /home/elharo/google-cloud-java/google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferProto.java:[367,59] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /home/elharo/google-cloud-java/google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataTransferProto.java:[374,51] internalBuildGeneratedFileFrom(java.lang.String[],com.google.protobuf.Descriptors.FileDescriptor[],com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner) in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /home/elharo/google-cloud-java/google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferProto.java:[103,51] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /home/elharo/google-cloud-java/google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferProto.java:[104,59] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /home/elharo/google-cloud-java/google-api-grpc/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/TransferProto.java:[111,51] internalBuildGeneratedFileFrom(java.lang.String[],com.google.protobuf.Descriptors.FileDescriptor[],com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner) in com.google.protobuf.Descriptors.FileDescriptor has been deprecated

**Comment by stephaniewang526** [comment]
@elharo : we're using a newer version of protobuf now. could you see if this is still happening? thanks!

**Comment by elharo** [comment]
Build it and see whether these warnings still appear.

**Comment by elharo** [comment]
I still see this:

datatransfer/proto-google-cloud-bigquerydatatransfer-v1/target/classes
[WARNING] bootstrap class path not set in conjunction with -source 1.7
[WARNING] /usr/local/google/home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceProto.java:[258,51] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /usr/local/google/home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceProto.java:[259,59] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /usr/local/google/home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceProto.java:[266,51] internalBuildGeneratedFileFrom(java.lang.String[],com.google.protobuf.Descriptors.FileDescriptor[],com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner) in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[INFO]

**Comment by elharo** [comment]
This seems to be fixed in the proto in google3. Where are we getting the proto from?

**Comment by stephaniewang526** [comment]
Our proto is auto-generated by synth tool from g3. Upon running `mvn verify` just now, I can see that this warning is no longer showing up. Hence, closing the ticket.

**Comment by elharo** [comment]
I still see it:

```
[INFO] Compiling 103 source files to /home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/target/classes
[WARNING] bootstrap class path not set in conjunction with -source 1.7
[WARNING] /home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceProto.java:[258,51] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceProto.java:[259,59] com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[WARNING] /home/elharo/java-bigquerydatatransfer/proto-google-cloud-bigquerydatatransfer-v1/src/main/java/com/google/cloud/bigquery/datatransfer/v1/DataSourceProto.java:[266,51] internalBuildGeneratedFileFrom(java.lang.String[],com.google.protobuf.Descriptors.FileDescriptor[],com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner) in com.google.protobuf.Descriptors.FileDescriptor has been deprecated
[INFO] 
```

**Comment by hzyi-google** [comment]
@elharo I am curious about what you mean by “this is fixed in google3”. How did you generate a library in google3? Did you use bazel build rules?

**Comment by elharo** [comment]
Just that when I looked at the source of the proto, I didn't find any references to `FileDescriptor.InternalDescriptorAssigner`.  A little digging might reveal the exact cl where this changed.

**Comment by hzyi-google** [comment]
Actually I suspect this is a behavior change in protobuf Java runtime: https://github.com/protocolbuffers/protobuf/blob/166652fc6f4f44e47153d96d7c790a06a65a2617/java/core/src/main/java/com/google/protobuf/Descriptors.java#L487-L488

I don't know what protoc's deprecation policy is but if it's for backward-compatibility we should expect no protoc-generated code to use it in next release. We probably need to check with protobuf team on this.

**Comment by stephaniewang526** [comment]
Reached out to protobuf team -- there is no plan to remove deprecated code from protoc auto-generated code in the forseeable future. The reason is for ABI compatibility. They recommended us to ignore the warnings.

**Comment by stephaniewang526** [comment]
Closing per comment above.
