### ISSUE TITLE
Get errors collection easily from TransferRun

### ISSUE THREAD

**Issue by robynnason** [googleapis/java-bigquerydatatransfer#1250]
Thanks for stopping by to let us know something could be better!

**Is your feature request related to a problem? Please describe.**
It's very difficult to debug issues in a data transfer run when the error message only states ```Error while reading data, error message: JSON table encountered too many errors, giving up. Rows: 1; errors: 1. Please look into the errors[] collection for more details``` 
There are no other logs in the run history that indicate what/where that error collection is. To try to do this programmatically in Java is also seemingly impossible, getting error messages from the TransferRun's `getErrorStatusOrBuilder` provides the same message as above, with no other details. I have seem some indication I could use the bq cli to do this, but my use case needs this to be done using Java. 

**Describe the solution you'd like**
The TransferRun should have a function that returns the errors[] collection. It should also show the errors[] collection in the UI. 

**Describe alternatives you've considered**
Instead of the log stating to look into the errors[] collection, maybe it could just include the errors there. 

**Additional context**
Any other context or screenshots about the feature request.

**Comment by meredithslota** [comment]
Hi there — thank you for reporting this! The client is passing through errors from the backend, so I will report this internally to see if there's something we can do to provide better errors here. I agree that this isn't that helpful, especially if the `errors[] collection` isn't accessible easily.

**Comment by meredithslota** [comment]
Internal feature request: b/230858298
