### ISSUE TITLE
Support AWS S3 Gov cloud

### ISSUE THREAD

**Issue by apptio-speravali** [googleapis/java-bigquerydatatransfer#1412]
**Is your feature request related to a problem? Please describe.**
Not able to move data from AWS S3 GOV to Bigquery

**Describe the solution you'd like**
Support AWS S3 Goc Cloud

**Describe alternatives you've considered**
No

**Comment by meredithslota** [comment]
@apptio-speravali Can you tell us more about this? How are you trying to move the data? What issues are you encountering? Amazon S3 transfers are supported via the Data Transfer Service: https://cloud.google.com/bigquery-transfer/docs/s3-transfer
